import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'], variable: '--font-inter' })

export const metadata: Metadata = {
  title: 'Template App Next.js',
  description: 'Generated by create next app configurated by André Felipe',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt-BR">
      <body
        className={[inter.className, 'flex min-h-screen flex-1 flex-col'].join(
          ' ',
        )}
      >
        {children}
      </body>
    </html>
  )
}
